# Generated by Django 4.1.5 on 2023-06-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='Student',
        ),
    ]
